import os, re, json
base = r'C:\PHASE2\Koha_Port'
swagger_dir = os.path.join(base, 'koha-original', 'api', 'v1', 'swagger', 'paths')
# Map swagger files to modules per MIGRATION_MASTER_PROMPT
swagger_to_module = {
    'acquisitions_baskets.yaml': 'koha-java-acquisitions',
    'acquisitions_edifiles.yaml': 'koha-java-acquisitions',
    'acquisitions_funds.yaml': 'koha-java-acquisitions',
    'acquisitions_orders.yaml': 'koha-java-acquisitions',
    'acquisitions_vendors.yaml': 'koha-java-acquisitions',
    'acquisitions_vendors_config.yaml': 'koha-java-acquisitions',
    'acquisitions_vendors_extended_attribute_types.yaml': 'koha-java-acquisitions',
    'acquisitions_vendor_issues.yaml': 'koha-java-acquisitions',
    'additional_contents.yaml': 'koha-java-admin',
    'advancededitormacros.yaml': 'koha-java-admin',
    'article_requests.yaml': 'koha-java-circulation',
    'auth.yaml': 'koha-java-auth',
    'authorised_values.yaml': 'koha-java-admin',
    'authorised_value_categories.yaml': 'koha-java-admin',
    'authorities.yaml': 'koha-java-catalog',
    'biblios.yaml': 'koha-java-catalog',
    'biblios_item_groups.yaml': 'koha-java-catalog',
    'biblios_merge.yaml': 'koha-java-catalog',
    'bookings.yaml': 'koha-java-circulation',
    'cash_registers.yaml': 'koha-java-finance',
    'checkouts.yaml': 'koha-java-circulation',
    'circulation_rules.yaml': 'koha-java-circulation',
    'cities.yaml': 'koha-java-admin',
    'clubs.yaml': 'koha-java-patron',
    'config_file_transports.yaml': 'koha-java-admin',
    'config_smtp_servers.yaml': 'koha-java-admin',
    'deleted_biblios.yaml': 'koha-java-catalog',
    'erm_agreements.yaml': 'koha-java-erm',
    'erm_config.yaml': 'koha-java-erm',
    'erm_counter_files.yaml': 'koha-java-erm',
    'erm_counter_logs.yaml': 'koha-java-erm',
    'erm_counter_registries.yaml': 'koha-java-erm',
    'erm_custom_reports.yaml': 'koha-java-erm',
    'erm_default_usage_reports.yaml': 'koha-java-erm',
    'erm_documents.yaml': 'koha-java-erm',
    'erm_eholdings_packages.yaml': 'koha-java-erm',
    'erm_eholdings_packages_resources.yaml': 'koha-java-erm',
    'erm_eholdings_resources.yaml': 'koha-java-erm',
    'erm_eholdings_titles.yaml': 'koha-java-erm',
    'erm_eholdings_titles_resources.yaml': 'koha-java-erm',
    'erm_extended_attribute_types.yaml': 'koha-java-erm',
    'erm_licenses.yaml': 'koha-java-erm',
    'erm_sushi_services.yaml': 'koha-java-erm',
    'erm_usage_databases.yaml': 'koha-java-erm',
    'erm_usage_data_providers.yaml': 'koha-java-erm',
    'erm_usage_items.yaml': 'koha-java-erm',
    'erm_usage_platforms.yaml': 'koha-java-erm',
    'erm_usage_titles.yaml': 'koha-java-erm',
    'erm_users.yaml': 'koha-java-erm',
    'extended_attribute_types.yaml': 'koha-java-admin',
    'holds.yaml': 'koha-java-holds',
    'ill_backends.yaml': 'koha-java-ill',
    'ill_batches.yaml': 'koha-java-ill',
    'ill_batchstatuses.yaml': 'koha-java-ill',
    'ill_requests.yaml': 'koha-java-ill',
    'ill_users.yaml': 'koha-java-ill',
    'import_batches.yaml': 'koha-java-catalog',
    'import_batch_profiles.yaml': 'koha-java-catalog',
    'items.yaml': 'koha-java-catalog',
    'item_types.yaml': 'koha-java-catalog',
    'jobs.yaml': 'koha-java-batch',
    'libraries.yaml': 'koha-java-admin',
    'lists.yaml': 'koha-java-patron',
    'oauth.yaml': 'koha-java-auth',
    'patrons.yaml': 'koha-java-patron',
    'patrons_account.yaml': 'koha-java-patron',
    'patrons_checkouts.yaml': 'koha-java-patron',
    'patrons_extended_attributes.yaml': 'koha-java-patron',
    'patrons_holds.yaml': 'koha-java-patron',
    'patrons_hold_groups.yaml': 'koha-java-patron',
    'patrons_password.yaml': 'koha-java-patron',
    'patrons_recalls.yaml': 'koha-java-patron',
    'patron_categories.yaml': 'koha-java-patron',
    'preservation_config.yaml': 'koha-java-admin',
    'preservation_processings.yaml': 'koha-java-admin',
    'preservation_trains.yaml': 'koha-java-admin',
    'preservation_waiting_list.yaml': 'koha-java-admin',
    'public_csp_reports.yaml': 'koha-java-opac-gateway',
    'public_oauth.yaml': 'koha-java-auth',
    'public_patrons.yaml': 'koha-java-patron',
    'quotes.yaml': 'koha-java-acquisitions',
    'record_sources.yaml': 'koha-java-catalog',
    'return_claims.yaml': 'koha-java-circulation',
    'rotas.yaml': 'koha-java-circulation',
    'search_filters.yaml': 'koha-java-search',
    'sip2_accounts.yaml': 'koha-java-admin',
    'sip2_institutions.yaml': 'koha-java-admin',
    'sip2_system_preference_overrides.yaml': 'koha-java-admin',
    'status.yaml': 'koha-java-admin',
    'suggestions.yaml': 'koha-java-acquisitions',
    'tickets.yaml': 'koha-java-admin',
    'transfer_limits.yaml': 'koha-java-admin',
}
# Count per module
from collections import Counter
module_counts = Counter(swagger_to_module.values())
with open(os.path.join(base, 'swagger_mapping.json'), 'w') as f:
    json.dump({'mapping': swagger_to_module, 'counts': dict(module_counts)}, f, indent=2)
