spring.application.name=koha-java-catalog
server.port=8081
server.servlet.context-path=/api/v1

# JPA / Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/koha
spring.datasource.username=koha
spring.datasource.password=koha
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
