spring.application.name=koha-java-circulation
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/koha
spring.datasource.username=koha
spring.datasource.password=koha
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jackson.serialization.write-dates-as-timestamps=false
