apiVersion: v1
kind: ConfigMap
metadata:
  name: koha-java-intranet-gateway-config
  namespace: koha
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/koha"
  SPRING_DATASOURCE_USERNAME: "koha_user"
  SPRING_DATASOURCE_PASSWORD: "koha_pass"
