apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: koha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: "koha"
            - name: POSTGRES_USER
              value: "koha_user"
            - name: POSTGRES_PASSWORD
              value: "koha_pass"
          ports:
            - containerPort: 5432
