apiVersion: apps/v1
kind: Deployment
metadata:
  name: koha-java-reporting
  namespace: koha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: koha-java-reporting
  template:
    metadata:
      labels:
        app: koha-java-reporting
    spec:
      containers:
        - name: koha-java-reporting
          image: shailahir/koha-java-reporting:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: koha-java-reporting-config
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
